### ISSUE TITLE
not saving

### ISSUE THREAD

**Issue by Brabus453** [Mojito-Fivem/qb-gangs#1]
i have small issue

all is working, but when i set a player into a gang, when he logout or leaves the city, when he rejoins, gang status is gone. so the player is not in gang anymore...

any idea?

**Comment by Brabus453** [comment]
also doorlocks do not work. doors just stay open

**Comment by Mojito-Fivem** [comment]
Issue with your framework not my script.

**Comment by Brabus453** [comment]
it is Qbus framework. so ....

**Comment by Mojito-Fivem** [comment]
Unrelated to this script.

**Comment by Brabus453** [comment]
How is it unrelated? Qb=qbus

**Comment by Mojito-Fivem** [comment]
I'm not going to explain how my script has nothing to do with your broken framework. Case closed

**Comment by Brabus453** [comment]
dude your script is broken , not the framework. but found the fix myself. goodluck finding it

**Comment by Mojito-Fivem** [comment]
One, if you're going to have that attitude GTFO from GitHub. Two, this script interacts with the existing systems within the framework to get gang data. There is no possible way my script can cause your gang to not save.
