### ISSUE TITLE
lost

### ISSUE THREAD

**Issue by morwic** [Mojito-Fivem/qb-gangs#12]
The "lost" gang in qb-core/share.lua is set "lostmc" and is not working to set stashs or garages.

**Comment by Mojito-Fivem** [comment]
This script doesn't use a shared.lua config, please read the README for the install instructions

**Comment by morwic** [comment]
I did :) then the lost is broke? I can not set a stash or garage. :(

**Comment by Mojito-Fivem** [comment]
"lost" is preconfigured, "lostmc" is something you must have made and configured wrong.

**Comment by morwic** [comment]
no look in shared.lua base install sir, it says lostmc for gang.  just trying to help out sir. that's why I even messaged you do to I was setting up the lost and it did not work. but the other gangs did.
