### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Belorico** [Mojito-Fivem/qb-gangs#14]
Did the update on qb-gangs and i`m having this error.

https://user-images.githubusercontent.com/4929196/128533426-1d39c0a7-a90e-473
![unknown](https://user-images.githubusercontent.com/4929196/128534230-afa86c32-b0e2-4821-a5e1-d4617a767cc7.png)

**Comment by Mojito-Fivem** [comment]
Your QBCore.Functions.GetPlayer() function is broken

**Comment by Belorico** [comment]
I have everything updated on QBCore and default. Probably some of the last QBCore updates broke it. Will you check it?

**Comment by Belorico** [comment]
![image](https://user-images.githubusercontent.com/4929196/128537142-d666ecf3-6a97-4609-889e-664c5674b6e6.png)

**Comment by Mojito-Fivem** [comment]
This is for qbus framework, if you're using the new 'QBCore' it probably isn't gonna work because they make breaking compatibility changes :)

**Comment by Belorico** [comment]
The description you have is this one:

Gangs for QB-Core with Gang Support instead of Jobs, supports infinately scaling gangs. Super optimised down to 0.01ms idle with a gang peaking at 0.04ms when drawing or inside of a territory zone, 0.00ms at idle as a civilian.

You could probably fix it in 2min ;)

Come on, i want to test it properly and i have some ideas for territories

**Comment by Mojito-Fivem** [comment]
You're pulling a quote that's not even relavent to the isse. In it's current state, this territories works but I won't be working on it.

**Comment by Belorico** [comment]
Just because you said its for qbus, but in description you have qbcore. Not trying to be a pain in the ass, sorry man. Just trying to have this working and because you do a good work

**Comment by Mojito-Fivem** [comment]
Yeah because this repo has been up longer than this qbcore shit has been around

**Comment by Matetv** [comment]
Is this for the QBCore Framework now?
https://github.com/orgs/qbcore-framework/

**Comment by Mojito-Fivem** [comment]
No this is for qbus framework.

**Comment by Insaneshane99** [comment]
I find this funny that you advertise qb-core then say qbus only in your posts, I cant even find a download for qbus core all redirect to qb-core so why are you eveloping for qbus if everyones using qb-core? not trying to be an ass i just think you should atleast give us some idea how to fix this issue

**Comment by Mojito-Fivem** [comment]
@Insaneshane99 Look at the version history on this repository before commenting please. This repository was created 10 **months** before this "QBCore" stuff started on the forums. This repository was created and is only designed for the **original** qbus framework, hereafter qb-core. This has only been tested on and designed for qb-core and now there's a sudden influx of people using this new "QBCore" stuff from the forums which isn't the same thing and is basically an esx legacy clone. I don't maintain this project anymore and I'm not going to adapt it to work with this new interpretation of the qbus framework.

The **only** version that this repository supports is the original qb-core, nothing else.
