### ISSUE TITLE
wrong gang names on config.js

### ISSUE THREAD

**Issue by macxitotruck** [Mojito-Fivem/qb-gangs#23]
gang.js  example [gang name] is = thefamily 

but in config.js u put = families 
 --------------------------         have to change families to thefamily  in config.js . otherwise cannot see marker -------
example of thread . 

         if isLoggedIn and PlayerGang.name ~= "none" then
            print(PlayerGang.name)   --- gang name [ thefamily]
        	if Config.Gangs[PlayerGang.name] ~= nil then
	            v = Config.Gangs[PlayerGang.name]["VehicleSpawner"]    --- overhere cannot find gang on config since it is 
                                                                                                                      register as familes 

current config 
{
  "families": {            --change to thefamily
    "VehicleSpawner": {
      "vehicles": {

**Comment by Mojito-Fivem** [comment]
Open a PR
