### ISSUE TITLE
Errors after updateing QB-

### ISSUE THREAD

**Issue by jawsoccer** [Mojito-Fivem/qb-gangs#24]
[    c-scripting-core] Creating script environments for qb-gangs
[     script:qb-gangs] Error loading script server/main.lua in resource qb-gangs: @qb-gangs/server/main.lua:4: attempt to index a nil value (global 'QBCore')
[     script:qb-gangs] stack traceback:
[     script:qb-gangs] 	@qb-gangs/server/main.lua:4: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[     script:qb-gangs] Error loading script server/territories.lua in resource qb-gangs: @qb-gangs/server/territories.lua:87: attempt to index a nil value (global 'QBCore')
[     script:qb-gangs] stack traceback:
[     script:qb-gangs] 	@qb-gangs/server/territories.lua:87: in main chunk
[    c-scripting-core] Failed to load script server/territories.lua.

**Comment by jawsoccer** [comment]
I believe QB updated some calls and this may have broken this resource

**Comment by Mojito-Fivem** [comment]
This resource isn't guaranteed to be compatible with the newer qbcore, this repo is almost a year old. These new guys have come along and maintain the framework but don't make it backwards compatible.
