### ISSUE TITLE
DrawMarker

### ISSUE THREAD

**Issue by piliatchoo** [Mojito-Fivem/qb-gangs#3]
Hello brother, I have a suggestion
How to make the stash and garage
color with DrawMarker with gang color
garage car = vagous with

**Comment by piliatchoo** [comment]
DrawMarker(2, v["coords"].x, v["coords"].y, v["coords"].z - 0.2 , 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.2, 0.15, 200, 200, 200, 222, false, false, false, true, false, false, false)

link this color with 

            ["colours"] = {
                ["primary"] = {
                    r = 179,
                    g = 176, 
                    b = 37
                },
                ["secondary"] = { 
                    r = 0,
                    b = 0, 
                    g = 0
                }

**Comment by piliatchoo** [comment]
and add
SetVehicleNumberPlateText(veh, "     2character with name gang             "..tostring(math.random(100, 999)))

**Comment by piliatchoo** [comment]
and
SetRelationshipBetweenGroups

**Comment by Mojito-Fivem** [comment]
Make a Pull Request
