### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by niels377** [Mojito-Fivem/qb-gangs#4]
Everything works but it doesnt save. When i create a gang and if i add people its gone after server restart.

**Comment by Mojito-Fivem** [comment]
Can you submit a repro? And send me your gangs.json before and after.

**Comment by niels377** [comment]
Sorry what do you mean with repro. Im very new to coding and making a server.

**Comment by Mojito-Fivem** [comment]
A demonstration of reproduction

**Comment by niels377** [comment]
is just kept everything as it was followed al steps didnt change anything just adjusted to my own core gangs.json isnt changed. is it possible it doesnt save in my database?

**Comment by Mojito-Fivem** [comment]
Did you rename qb-gangs?

**Comment by niels377** [comment]
yes i did

**Comment by Mojito-Fivem** [comment]
There's your problem then

**Comment by niels377** [comment]
should the main folder be qb-gangs

**Comment by Mojito-Fivem** [comment]
If you rename it then your core is going to try to read from a file in the wrong directory, if you don't know how to correct that then just leave it as qb-gangs

**Comment by niels377** [comment]
in the files also keep qb-gangs or change to core

**Comment by Mojito-Fivem** [comment]
just leave the resource name as qb-gangs

**Comment by niels377** [comment]
im gonna try

**Comment by niels377** [comment]
![problem](https://user-images.githubusercontent.com/77588813/112722062-920d2000-8ec4-11eb-8f3d-24d6d975b92a.PNG)
self.Functions.SetGang = function(gang)
		local gang = gang:lower()
		if RSCore.Shared.Gangs[gang] ~= nil then
			self.PlayerData.gang.name = gang
			self.PlayerData.gang.label = RSCore.Shared.Gangs[gang].label
			self.Functions.UpdatePlayerData()
			TriggerClientEvent("RSCore:Client:OnGangUpdate", self.PlayerData.source, self.PlayerData.gang)
		end
	end

**Comment by niels377** [comment]
this happend when i try to add myself into a gang a created

**Comment by Mojito-Fivem** [comment]
Yeah your framework isn't loading the gangs properly. This is why we don't rename things when we don't know what we're doing.

**Comment by niels377** [comment]
but i thought i had to rename the script to make it work with my framework? but do i have to keep everything qb-gangs

**Comment by Mojito-Fivem** [comment]
You'll need to fix the SetGangs event handlers to work with your framework and fix your shared.lua to read from qb-core/gangs.json

**Comment by niels377** [comment]
sure i will try thank you for helping me
